apiVersion: apps/v1
kind: Deployment
metadata:
  name: iac-python-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: iac-python-deployment
  template:
    metadata:
      labels:
        app: iac-python-deployment
    spec:
      containers:
      - name: iac-python
        image: codingforentrepreneurs/iac-python:latest
        env:
         - name: PORT
           value: "8181"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8181


---

apiVersion: v1
kind: Service
metadata:
  name: iac-python
spec:
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 80 
      targetPort: 8181
  selector:
    app: iac-python
